### ISSUE TITLE
Workflows shouldn't fail when secrets aren't available

### ISSUE THREAD

**Issue by jsoref** [OctopusDeploy/docs#2018]
I have a fork of this repository with actions enabled (this is a common state for forks and should be encouraged).

When I refreshed `main`, the [`build-astro`](https://github.com/jsoref/OctopusDeploy-docs/actions/runs/6381706010/workflow) workflow [failed](https://github.com/jsoref/OctopusDeploy-docs/actions/runs/6381706010).

It's possible to avoid failing by either checking for secrets -- this requires a bit of:

```yaml
env:
  has_secret1: ${{ secrets.secret1 != '' }}
  if: ${{ env.has_secret1 }}
```

_or_ using an `if: github.repository_owner` -- I don't recommend this practice, but it does work if you don't want to let forks set up their own secrets to run workflows.
